# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'capritools2', '0001_initial'), (b'capritools2', '0002_auto_20170531_1617'), (b'capritools2', '0003_auto_20170531_1629'), (b'capritools2', '0004_auto_20170531_1635'), (b'capritools2', '0005_region'), (b'capritools2', '0006_constellation_system'), (b'capritools2', '0007_auto_20170531_2146'), (b'capritools2', '0008_dscan_dscanobject'), (b'capritools2', '0009_auto_20170531_2252'), (b'capritools2', '0010_auto_20170531_2301'), (b'capritools2', '0011_auto_20170602_1503'), (b'capritools2', '0012_auto_20170602_2047')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='capritools2.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mass', models.FloatField()),
                ('volume', models.FloatField()),
                ('capacity', models.FloatField()),
                ('raceID', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
                ('iconID', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.IntegerField(null=True)),
                ('hasTypes', models.NullBooleanField()),
                ('parentGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.MarketGroup')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='marketGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.MarketGroup'),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='iconID',
            new_name='icon',
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.FloatField(null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Region')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.FloatField(null=True)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Constellation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Dscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=12)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.System')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DscanObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('distance', models.FloatField(null=True)),
                ('dscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanObjects', to='capritools2.Dscan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanObjects', to='capritools2.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='dscan',
            name='key',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='dscan',
            name='key',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='capritools2.Group'),
        ),
    ]
