# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='capritools2.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mass', models.FloatField()),
                ('volume', models.FloatField()),
                ('capacity', models.FloatField()),
                ('raceID', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
                ('iconID', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('iconID', models.IntegerField(null=True)),
                ('hasTypes', models.BooleanField()),
                ('parentGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.MarketGroup')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='marketGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.MarketGroup'),
        ),
    ]
