# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0001_squashed_0012_auto_20170602_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscanobject',
            name='distance',
            field=models.BigIntegerField(null=True),
        ),
    ]
