# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='iconID',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='marketgroup',
            old_name='iconID',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='marketgroup',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
