# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0003_auto_20170531_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgroup',
            name='hasTypes',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
