# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0003_auto_20170602_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscanobject',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
