# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0004_auto_20170531_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.FloatField(null=True)),
            ],
        ),
    ]
