# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0005_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.FloatField(null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Region')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('factionID', models.IntegerField(null=True)),
                ('radius', models.FloatField(null=True)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Constellation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Region')),
            ],
        ),
    ]
