# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0006_constellation_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
