# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0006_auto_20170603_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localscanchar',
            name='character',
        ),
        migrations.AddField(
            model_name='localscanchar',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localscanchar',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localChars', to='capritools2.Alliance'),
        ),
        migrations.AlterField(
            model_name='localscanchar',
            name='corporation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localChars', to='capritools2.Corporation'),
        ),
        migrations.AlterField(
            model_name='localscanchar',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localChars', to='capritools2.Faction'),
        ),
    ]
