# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0007_auto_20170603_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localscanchar',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localChars', to='capritools2.Character'),
        ),
    ]
