# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capritools2', '0007_auto_20170531_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=12)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.System')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DscanObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('distance', models.FloatField()),
                ('dscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Dscan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Item')),
            ],
        ),
    ]
