# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0008_dscan_dscanobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscanobject',
            name='dscan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanObjects', to='capritools2.Dscan'),
        ),
    ]
