# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0008_auto_20170603_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localscanchar',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
