# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0009_auto_20170531_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscan',
            name='key',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
