# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0010_remove_localscanchar_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Alliance')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Corporation')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='capritools2.LocalScan')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together=set([('corporation', 'alliance')]),
        ),
    ]
