# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0011_auto_20170602_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscan',
            name='key',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='dscanobject',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanObjects', to='capritools2.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='capritools2.Group'),
        ),
    ]
