# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0014_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paste',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
