# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0015_auto_20170605_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='salt',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
