# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0016_paste_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
