# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0018_item_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
