# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0019_auto_20170606_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscan',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='localscan',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
