# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capritools2', '0020_auto_20170607_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('leadership', models.IntegerField()),
                ('wing_command', models.IntegerField()),
                ('fleet_command', models.IntegerField()),
                ('boss', models.BooleanField(default=False)),
                ('alliance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.Alliance')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Corporation')),
            ],
        ),
        migrations.CreateModel(
            name='FleetScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FleetSquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='capritools2.FleetScan')),
            ],
        ),
        migrations.CreateModel(
            name='FleetWing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='capritools2.FleetScan')),
            ],
        ),
        migrations.AddField(
            model_name='fleetsquad',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='capritools2.FleetWing'),
        ),
        migrations.AddField(
            model_name='fleetmember',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='capritools2.FleetScan'),
        ),
        migrations.AddField(
            model_name='fleetmember',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Item'),
        ),
        migrations.AddField(
            model_name='fleetmember',
            name='squad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='capritools2.FleetSquad'),
        ),
        migrations.AddField(
            model_name='fleetmember',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.System'),
        ),
        migrations.AddField(
            model_name='fleetmember',
            name='wing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='capritools2.FleetWing'),
        ),
    ]
