# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0022_auto_20170607_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='ticker',
            field=models.CharField(db_index=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='ticker',
            field=models.CharField(db_index=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='fleetmember',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
