# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0024_fleetmember_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetmember',
            options={'ordering': ['wing', 'squad', 'command', 'name']},
        ),
        migrations.AlterModelOptions(
            name='fleetsquad',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fleetwing',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='system',
            name='sun',
            field=models.ForeignKey(default=3802, on_delete=django.db.models.deletion.CASCADE, to='capritools2.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleetmember',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleetMembers', to='capritools2.Alliance'),
        ),
        migrations.AlterField(
            model_name='fleetmember',
            name='corporation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleetMembers', to='capritools2.Corporation'),
        ),
        migrations.AlterField(
            model_name='fleetmember',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleetMembers', to='capritools2.Item'),
        ),
        migrations.AlterField(
            model_name='fleetmember',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleetMembers', to='capritools2.System'),
        ),
    ]
