# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('capritools2', '0026_auto_20170611_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
            preserve_default=False,
        ),
    ]
