# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0029_auto_20170611_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=64, null=True),
        ),
    ]
