# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0030_auto_20170611_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='free_move',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='motd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='registered',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='voice_enabled',
            field=models.NullBooleanField(),
        ),
    ]
