# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0032_auto_20170612_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
