# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0034_fleet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
