# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0038_auto_20170612_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet_MemberEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Character')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Fleet')),
            ],
        ),
    ]
