# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0040_fleet_shipchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet_Jump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Character')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capritools2.Fleet')),
                ('from_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_system', to='capritools2.System')),
                ('to_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_system', to='capritools2.System')),
            ],
        ),
    ]
