# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0041_fleet_jump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet_member',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_members', to='capritools2.Item'),
        ),
        migrations.AlterField(
            model_name='fleet_member',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_members', to='capritools2.System'),
        ),
    ]
