# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0042_auto_20170613_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet_member',
            name='keys',
            field=models.CharField(db_index=True, default='asd', max_length=7),
            preserve_default=False,
        ),
    ]
