# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0043_fleet_member_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet_member',
            old_name='keys',
            new_name='key',
        ),
    ]
