# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0045_auto_20170613_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleet_jump',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='fleet_member',
            options={'ordering': ['character__name']},
        ),
        migrations.AlterModelOptions(
            name='fleet_memberevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='fleet_shipchange',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='fleet_squad',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fleet_wing',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='fleet_jump',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumps', to='capritools2.Fleet'),
        ),
        migrations.AlterField(
            model_name='fleet_member',
            name='takes_fleet_warp',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fleet_memberevent',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='capritools2.Fleet'),
        ),
    ]
