# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0046_auto_20170613_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleet_shipchange',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_changes', to='capritools2.Fleet'),
        ),
    ]
