# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capritools2', '0048_auto_20170615_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='sun',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capritools2.Item'),
        ),
    ]
